_core:
  default_config_hash: QUZHrnAKd4ixgLLVtD3JrrBMlwbmJ6VU-qKcOMDKatw
buttons_size: 32
additional_html: "<a class=\"a2a_button_email\"></a>\r\n<a class=\"a2a_button_linkedin\"></a>\r\n<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_viber\"></a>\r\n\r\n"
additional_css: ''
additional_js: ''
universal_button: default
custom_universal_button: ''
universal_button_placement: before
entities:
  media: 0
  node: 1
  comment: 0
  block_content: 1
  contact_message: 0
  file: 0
  menu_link_content: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  paragraph: 0
