_core:
  default_config_hash: 6r9KA1Wa13n0_l8yU0AP5GKn49rkKotIYeyrdd22qac
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://logo-01_0.png'
  use_default: false
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://www.linkedin.com/in/shirley-zamoraj/'
youtube_url: 'https://www.youtube.com/user/Google'
vk_url: ''
whatsapp_url: ''
github_url: 'https://github.com/shirleyzj16'
telegram_url: ''
vimeo_url: ''
slider_show: 1
slider_image:
  - '4'
slider_time: '5000'
slider_dots: 'true'
slider_code: ''
front_sidebar: 1
google_font: local
comment_user_pic: 0
node_author_pic: 0
node_tags: 0
copyright_text: 1
scrolltotop_on: 1
css_extra: 0
css_code: ''
